CREATE TABLE `supplierBankAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`tenantId` int NOT NULL,
	`bankName` varchar(100),
	`bankCode` varchar(10),
	`agency` varchar(20),
	`accountNumber` varchar(30),
	`accountType` enum('corrente','poupanca','pagamento') DEFAULT 'corrente',
	`pixKey` varchar(255),
	`pixKeyType` enum('cpf','cnpj','email','telefone','aleatoria'),
	`accountHolder` varchar(255),
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `supplierBankAccounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplierDocuments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`tenantId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`documentType` enum('contrato','tabela_precos','certificado','outros') DEFAULT 'outros',
	`fileUrl` varchar(1000) NOT NULL,
	`fileKey` varchar(500) NOT NULL,
	`mimeType` varchar(100),
	`fileSizeBytes` int,
	`uploadedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `supplierDocuments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`companyType` enum('juridica','fisica') NOT NULL DEFAULT 'juridica',
	`corporateName` varchar(255) NOT NULL,
	`tradeName` varchar(255),
	`cnpj` varchar(18),
	`cpf` varchar(14),
	`stateRegistration` varchar(50),
	`municipalRegistration` varchar(50),
	`cnae` varchar(20),
	`foundingDate` varchar(10),
	`isActive` boolean NOT NULL DEFAULT true,
	`isPreferred` boolean NOT NULL DEFAULT false,
	`emailPrimary` varchar(320),
	`emailSecondary` varchar(320),
	`phoneLandline` varchar(20),
	`phoneMobile` varchar(20),
	`phoneWhatsapp` varchar(20),
	`website` varchar(500),
	`contactName` varchar(255),
	`contactRole` varchar(100),
	`zipCode` varchar(9),
	`street` varchar(255),
	`number` varchar(20),
	`complement` varchar(100),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`country` varchar(50) DEFAULT 'Brasil',
	`supplierCategory` json,
	`paymentTerms` varchar(100),
	`paymentMethodPreferred` enum('pix','boleto','transferencia','cartao'),
	`minimumOrder` decimal(12,2),
	`averageDeliveryDays` int,
	`discountPercentage` decimal(5,2),
	`creditLimit` decimal(12,2),
	`observationsCommercial` text,
	`brandsSupplied` json,
	`productLines` json,
	`catalogUrl` varchar(500),
	`firstPurchaseDate` varchar(10),
	`lastPurchaseDate` varchar(10),
	`totalPurchasesAmount` decimal(14,2) DEFAULT '0',
	`rating` int,
	`ratingNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
