CREATE TABLE `companySettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`logoUrl` varchar(1000),
	`logoKey` varchar(500),
	`companyName` varchar(255),
	`tradeName` varchar(255),
	`cnpj` varchar(18),
	`stateRegistration` varchar(50),
	`municipalRegistration` varchar(50),
	`phonePrimary` varchar(20),
	`phoneSecondary` varchar(20),
	`whatsapp` varchar(20),
	`emailPrimary` varchar(320),
	`emailSecondary` varchar(320),
	`website` varchar(255),
	`zipCode` varchar(9),
	`street` varchar(255),
	`number` varchar(20),
	`complement` varchar(100),
	`neighborhood` varchar(100),
	`city` varchar(100),
	`state` varchar(2),
	`primaryColor` varchar(7) DEFAULT '#1B4F8A',
	`secondaryColor` varchar(7) DEFAULT '#C4733A',
	`documentHeaderText` text,
	`documentFooterText` text,
	`warrantyText` text,
	`osTerms` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `companySettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `companySettings_tenantId_unique` UNIQUE(`tenantId`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`cpf` varchar(14),
	`rg` varchar(20),
	`birthDate` varchar(10),
	`phone` varchar(20),
	`email` varchar(320),
	`photoUrl` varchar(1000),
	`photoKey` varchar(500),
	`address` text,
	`role` enum('technician','attendant','manager','admin') NOT NULL DEFAULT 'technician',
	`specialties` json,
	`hireDate` varchar(10),
	`isActive` boolean NOT NULL DEFAULT true,
	`userAccountId` int,
	`commissionType` enum('none','percentage','fixed') NOT NULL DEFAULT 'none',
	`commissionPercentage` decimal(5,2),
	`commissionFixedValue` decimal(10,2),
	`commissionBase` enum('services_only','services_and_parts','total') DEFAULT 'services_only',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employees_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `ordensServico` ADD `attendantId` int;