/**
 * Seed do Plano de Contas Gerencial — executado ao criar um novo tenant.
 * Estrutura hierárquica conforme especificação do produto.
 */

export const CHART_OF_ACCOUNTS_SEED = [
  // ── RECEITAS ─────────────────────────────────────────────────────────────
  { code: "1",     name: "RECEITAS",                         type: "receita" as const, parentCode: null },
  { code: "1.1",   name: "Receita de Serviços",              type: "receita" as const, parentCode: "1" },
  { code: "1.1.1", name: "Mão de Obra OS",                   type: "receita" as const, parentCode: "1.1" },
  { code: "1.1.2", name: "Diagnóstico",                      type: "receita" as const, parentCode: "1.1" },
  { code: "1.1.3", name: "Visita Técnica",                   type: "receita" as const, parentCode: "1.1" },
  { code: "1.2",   name: "Receita de Peças e Produtos",      type: "receita" as const, parentCode: "1" },
  { code: "1.2.1", name: "Venda de Peças",                   type: "receita" as const, parentCode: "1.2" },
  { code: "1.2.2", name: "Venda de Acessórios",              type: "receita" as const, parentCode: "1.2" },
  { code: "1.3",   name: "Outras Receitas",                  type: "receita" as const, parentCode: "1" },
  { code: "1.3.1", name: "Desconto de Fornecedor",           type: "receita" as const, parentCode: "1.3" },
  { code: "1.3.2", name: "Receitas Diversas",                type: "receita" as const, parentCode: "1.3" },

  // ── CUSTOS ───────────────────────────────────────────────────────────────
  { code: "2",     name: "CUSTOS",                           type: "custo" as const, parentCode: null },
  { code: "2.1",   name: "Custo de Peças",                   type: "custo" as const, parentCode: "2" },
  { code: "2.1.1", name: "Peças Compradas para OS",          type: "custo" as const, parentCode: "2.1" },
  { code: "2.1.2", name: "Peças de Estoque Utilizadas",      type: "custo" as const, parentCode: "2.1" },
  { code: "2.2",   name: "Custo de Serviços Terceirizados",  type: "custo" as const, parentCode: "2" },
  { code: "2.2.1", name: "Subcontratação Técnica",           type: "custo" as const, parentCode: "2.2" },

  // ── DESPESAS OPERACIONAIS ─────────────────────────────────────────────────
  { code: "3",     name: "DESPESAS OPERACIONAIS",            type: "despesa" as const, parentCode: null },
  { code: "3.1",   name: "Pessoal",                          type: "despesa" as const, parentCode: "3" },
  { code: "3.1.1", name: "Salários",                         type: "despesa" as const, parentCode: "3.1" },
  { code: "3.1.2", name: "Pró-labore",                       type: "despesa" as const, parentCode: "3.1" },
  { code: "3.1.3", name: "Encargos Sociais",                 type: "despesa" as const, parentCode: "3.1" },
  { code: "3.1.4", name: "Vale Transporte",                  type: "despesa" as const, parentCode: "3.1" },
  { code: "3.1.5", name: "Vale Refeição",                    type: "despesa" as const, parentCode: "3.1" },
  { code: "3.2",   name: "Instalações",                      type: "despesa" as const, parentCode: "3" },
  { code: "3.2.1", name: "Aluguel",                          type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.2", name: "Condomínio",                       type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.3", name: "IPTU",                             type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.4", name: "Energia Elétrica",                 type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.5", name: "Água",                             type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.6", name: "Internet",                         type: "despesa" as const, parentCode: "3.2" },
  { code: "3.2.7", name: "Telefone",                         type: "despesa" as const, parentCode: "3.2" },
  { code: "3.3",   name: "Equipamentos e Ferramentas",       type: "despesa" as const, parentCode: "3" },
  { code: "3.3.1", name: "Manutenção de Equipamentos",       type: "despesa" as const, parentCode: "3.3" },
  { code: "3.3.2", name: "Compra de Ferramentas",            type: "despesa" as const, parentCode: "3.3" },
  { code: "3.3.3", name: "Depreciação",                      type: "despesa" as const, parentCode: "3.3" },
  { code: "3.4",   name: "Administrativo",                   type: "despesa" as const, parentCode: "3" },
  { code: "3.4.1", name: "Material de Escritório",           type: "despesa" as const, parentCode: "3.4" },
  { code: "3.4.2", name: "Software e Assinaturas",           type: "despesa" as const, parentCode: "3.4" },
  { code: "3.4.3", name: "Contabilidade",                    type: "despesa" as const, parentCode: "3.4" },
  { code: "3.4.4", name: "Honorários",                       type: "despesa" as const, parentCode: "3.4" },
  { code: "3.4.5", name: "Taxas Bancárias",                  type: "despesa" as const, parentCode: "3.4" },
  { code: "3.5",   name: "Comercial e Marketing",            type: "despesa" as const, parentCode: "3" },
  { code: "3.5.1", name: "Publicidade",                      type: "despesa" as const, parentCode: "3.5" },
  { code: "3.5.2", name: "Plataformas Digitais",             type: "despesa" as const, parentCode: "3.5" },
  { code: "3.5.3", name: "Material Gráfico",                 type: "despesa" as const, parentCode: "3.5" },
  { code: "3.6",   name: "Impostos e Taxas",                 type: "despesa" as const, parentCode: "3" },
  { code: "3.6.1", name: "Simples Nacional",                 type: "despesa" as const, parentCode: "3.6" },
  { code: "3.6.2", name: "ISS",                              type: "despesa" as const, parentCode: "3.6" },
  { code: "3.6.3", name: "Outras Taxas",                     type: "despesa" as const, parentCode: "3.6" },
  { code: "3.7",   name: "Financeiro",                       type: "despesa" as const, parentCode: "3" },
  { code: "3.7.1", name: "Juros Pagos",                      type: "despesa" as const, parentCode: "3.7" },
  { code: "3.7.2", name: "Tarifas",                          type: "despesa" as const, parentCode: "3.7" },
  { code: "3.7.3", name: "IOF",                              type: "despesa" as const, parentCode: "3.7" },
  { code: "3.8",   name: "Despesas Diversas",                type: "despesa" as const, parentCode: "3" },
  { code: "3.8.1", name: "Despesas Eventuais",               type: "despesa" as const, parentCode: "3.8" },
  { code: "3.8.2", name: "Outros",                           type: "despesa" as const, parentCode: "3.8" },
] as const;
